version: '3'
services:
  pufferpanel:
    image: jorisvos037/pufferpanel
    container_name: pufferpanel
    ports:
      - "8080:8080"
      - "25565:25565"
      - "5657:5657"
      - "5656:5656"
    environment:
      VIRTUAL_HOST: 127.0.0.1
      VIRTUAL_PORT: 8080
    restart: unless-stopped
